### PR TITLE
add pillar section

### PR DESCRIPTION
**Pull request by acchiang**
add pillar section with 3 pillars, featuring easily customizable icons and dummy text. 

new pillar section scss file as well. 
cross browser testing completed in chrome/ff/safari

### CODE REVIEW

**Comment by acchiang** [comment]
safari: image
ff: 
image
developed in chrome

**Comment by patkarns** [comment]
Works on opera as well. 

But when I shrink the window to half my screen, the icon overlaps with the text (happens on chrome, opera, firefox, safari)
Screen Shot 2020-08-17 at 12 54 17 PM

**Comment by tommytwm** [comment]
It works fine on Firefox on MacOS, however, there needs to be some css adjustments on the iPad Mini-esque screen size.
Screen Shot 2020-08-18 at 6 08 05 PM

**Comment by acchiang** [comment]
Thanks for the screenshots @patkarns @tommytwm! 

Here are the updated screenshots, following some code changes. :) 
Screen Shot 2020-08-18 at 10 53 52 PM
Screen Shot 2020-08-18 at 10 54 38 PM
Screen Shot 2020-08-18 at 10 54 46 PM
Screen Shot 2020-08-18 at 10 55 00 PM
Screen Shot 2020-08-18 at 10 55 06 PM
Screen Shot 2020-08-18 at 10 55 23 PM
Screen Shot 2020-08-18 at 10 55 27 PM
Screen Shot 2020-08-18 at 10 55 31 PM

**Pull request merged**
