### PR TITLE
Hero

### PR DESCRIPTION
**Pull request by tommytwm**
• Added Hero header + button
• Added Hero graphic + clouds
• Added Call-to-action arrow below the hero

### CODE REVIEW

**Comment by acchiang** [comment]
Thanks for making these changes @tommytwm! 
I noticed a new bug in your latest commit, I tried switching between your second to last and last commit. There is extra space below the footer. 
image

**Comment by tommytwm** [comment]
> Thanks for making these changes @tommytwm!
> I noticed a new bug in your latest commit, I tried switching between your second to last and last commit. There is extra space below the footer.
> image

Huh that's odd... I'll take a look at this and make the fixes

**Review by acchiang — COMMENTED** [review]
Looking good so far, great mobile responsiveness too :) Thanks for looking into the footer thing, let me know if I can help!

**Comment by tommytwm** [comment]
Bug has been fixed — there was a missing closing div tag for the "hero" section

**Review by acchiang — APPROVED** [review]
Looks good, thanks for making the changes! Should be good to merge!

**Pull request merged**
